excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://DestinationSNicole.github.io
title: DestinationSNicole
tagline: Say a little prayer....
description: You would never know if you met or talked to me that I struggled in my relationship with God, that I struggle in my faith, that I struggle with prayer.  <br />Travel with me to my Destination of faith, love, peace, joy, confidence, boldness, salvation through my highs, my lows and most importantly through prayer.
paginate: 5